### ISSUE TITLE
create a tag for QASM 2.0

### ISSUE THREAD

**Issue by Roger-luo** [Qiskit/openqasm#71] opened 2020-11-07 21:09 UTC
Hi I'm wondering if there could be a tag for QASM 2.0, which makes it easier to find specifications and examples for QASM 2.0?

Bests

**Comment by jaygambetta** [comment] 2020-11-09 14:53
Hi @Roger-luo  I agree that we need this going forward (4.0, 3.1 etc) and why we have moved to a live document. The issue is we never really made documentation for QASM 2.0 it was just the arxiv paper in RST form. We are trying to change our practices going forward and work with the community to define 3.0. (i will make this clear in the readme that qasm 3.0 is not finished yet)

An option could be just to make a branch that we call 2.0 that has 
1. examples folder
2. Readme with a link to the arxiv paper 

Would this work?

**Comment by jaygambetta** [comment] 2020-11-09 14:54
@blakejohnson, @ajavadia, and @levbishop could you give your thoughts on this as well.

**Comment by Roger-luo** [comment] 2020-11-09 23:08
Yeah I think given there are quite a few projects uses the examples in this repo to test QASM 2.0, it'd be nice to keep it easily accessible. A new branch would solve the problem, but I still think a tag would make things clearer, similar to other language specification, such as TOML: https://github.com/toml-lang/toml/releases

**Comment by jaygambetta** [comment] 2020-11-10 14:49
i know but tags giveen the history of the repo is not so simple as we never really did this.

**Comment by jaygambetta** [comment] 2020-11-10 15:05
thinking about it I think what we will do is go with a branch for major and a tag in that branch when we do a release for each minor, this way if there is a reason to go from qasm 2.0 to qasm 2.1 we can also do this within that branch. Given the history of qasm 2.0 the tag will be late but I think that is fine. @ismaelfaro do you agree.

**Comment by ismaelfaro** [comment] 2020-11-10 15:11
Yeah, we can keep tracking using the branch for major changes and Tags to tracking the minor ones too.

**Comment by jaygambetta** [comment] 2020-11-10 17:12
@Roger-luo closing as we have a branch now -- lets us know if there are still problems or things missing.

**Closed by jaygambetta** 2020-11-10 17:12 UTC
